// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THUCTAP.Data;

#nullable disable

namespace THUCTAP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806063519_HospitalDB")]
    partial class HospitalDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppActionGroup", b =>
                {
                    b.Property<int>("actionid")
                        .HasColumnType("int");

                    b.Property<int>("groupid")
                        .HasColumnType("int");

                    b.HasKey("actionid", "groupid");

                    b.HasIndex("groupid");

                    b.ToTable("Group_Action", (string)null);

                    b.HasData(
                        new
                        {
                            actionid = 1,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 2,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 3,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 4,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 5,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 1,
                            groupid = 2
                        },
                        new
                        {
                            actionid = 2,
                            groupid = 2
                        },
                        new
                        {
                            actionid = 4,
                            groupid = 2
                        },
                        new
                        {
                            actionid = 1,
                            groupid = 3
                        });
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.Property<int>("groupid")
                        .HasColumnType("int");

                    b.Property<int>("menuid")
                        .HasColumnType("int");

                    b.HasKey("groupid", "menuid");

                    b.HasIndex("menuid");

                    b.ToTable("Group_Menu", (string)null);

                    b.HasData(
                        new
                        {
                            groupid = 1,
                            menuid = 1
                        },
                        new
                        {
                            groupid = 1,
                            menuid = 2
                        },
                        new
                        {
                            groupid = 2,
                            menuid = 2
                        },
                        new
                        {
                            groupid = 2,
                            menuid = 8
                        },
                        new
                        {
                            groupid = 3,
                            menuid = 2
                        },
                        new
                        {
                            groupid = 3,
                            menuid = 8
                        });
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<int>("groupid")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("groupid", "userid");

                    b.HasIndex("userid");

                    b.ToTable("User_Group", (string)null);

                    b.HasData(
                        new
                        {
                            groupid = 1,
                            userid = 1
                        },
                        new
                        {
                            groupid = 2,
                            userid = 2
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.AppAction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "endpoint");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int>("menuId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "menuId");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "method");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("menuId");

                    b.ToTable("Actions");

                    b.HasAnnotation("Relational:JsonPropertyName", "action");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "USER_VIEW_LIST",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7013),
                            endpoint = "/api/users",
                            label = "Danh sách ",
                            menuId = 2,
                            method = "GET",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7013)
                        },
                        new
                        {
                            id = 2,
                            code = "USER_VIEW_DETAIL",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7016),
                            endpoint = "/api/users/{id}",
                            label = "Chi tiết ",
                            menuId = 2,
                            method = "GET",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7016)
                        },
                        new
                        {
                            id = 3,
                            code = "USER_ADD",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7018),
                            endpoint = "/api/users",
                            label = "Thêm mới ",
                            menuId = 2,
                            method = "POST",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7018)
                        },
                        new
                        {
                            id = 4,
                            code = "USER_EDIT",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7019),
                            endpoint = "/api/users/{id}",
                            label = "Cập nhật ",
                            menuId = 2,
                            method = "PUT",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7020)
                        },
                        new
                        {
                            id = 5,
                            code = "USER_DEL",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7021),
                            endpoint = "/api/users/{id}",
                            label = "Xóa ",
                            menuId = 2,
                            method = "DELETE",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7021)
                        },
                        new
                        {
                            id = 6,
                            code = "GROUP_VIEW_LIST",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7023),
                            endpoint = "/api/groups",
                            label = "Danh sách nhóm",
                            menuId = 7,
                            method = "GET",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7023)
                        },
                        new
                        {
                            id = 7,
                            code = "GROUP_ADD",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7024),
                            endpoint = "/api/groups",
                            label = "Thêm nhóm",
                            menuId = 7,
                            method = "POST",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7024)
                        },
                        new
                        {
                            id = 8,
                            code = "GROUP_EDIT",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7025),
                            endpoint = "/api/groups/{id}",
                            label = "Sửa nhóm",
                            menuId = 7,
                            method = "PUT",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7026)
                        },
                        new
                        {
                            id = 9,
                            code = "GROUP_DEL",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7027),
                            endpoint = "/api/groups/{id}",
                            label = "Xóa nhóm",
                            menuId = 7,
                            method = "DELETE",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7027)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.FormField", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("colSpan")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "colSpan");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("entityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "entityName");

                    b.Property<string>("field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "field");

                    b.Property<bool>("isDetail")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isDetail");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int?>("menuId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "menuId");

                    b.Property<string>("option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "option");

                    b.Property<string>("optionLabel")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "optionLabel");

                    b.Property<string>("optionValue")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "optionValue");

                    b.Property<int>("sortOrder")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "sortOrder");

                    b.Property<string>("subField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "subField");

                    b.Property<string>("tabName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tabName");

                    b.Property<string>("tagField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tagField");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("menuId");

                    b.ToTable("FormFields");

                    b.HasData(
                        new
                        {
                            id = 1,
                            colSpan = 6,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7125),
                            entityName = "User",
                            field = "username",
                            isDetail = false,
                            label = "Tên đăng nhập",
                            option = "",
                            sortOrder = 1,
                            subField = "",
                            tabName = "",
                            tagField = "",
                            type = "text",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7126)
                        },
                        new
                        {
                            id = 2,
                            colSpan = 6,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7130),
                            entityName = "User",
                            field = "department",
                            isDetail = false,
                            label = "Phòng ban",
                            option = "",
                            sortOrder = 2,
                            subField = "",
                            tabName = "",
                            tagField = "",
                            type = "select",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7130)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Group", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "ADMIN",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(6987),
                            name = "Quản trị hệ thống",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(6987)
                        },
                        new
                        {
                            id = 2,
                            code = "DOCTOR",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(6989),
                            name = "Bác sĩ",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(6989)
                        },
                        new
                        {
                            id = 3,
                            code = "Employee",
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(6990),
                            name = "Nhân viên",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(6990)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "icon");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int?>("parentId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "parentId");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "to");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("parentId");

                    b.ToTable("Menus");

                    b.HasAnnotation("Relational:JsonPropertyName", "children");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7074),
                            icon = "shield",
                            label = "SECURITY & SYSTEM",
                            to = "",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7074)
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7077),
                            icon = "users",
                            label = "EMPLOYEE MANAGEMENT",
                            to = "",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7077)
                        },
                        new
                        {
                            id = 3,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7079),
                            icon = "settings",
                            label = "ADMINISTRATION",
                            to = "",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7079)
                        },
                        new
                        {
                            id = 4,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7081),
                            icon = "shopping-cart",
                            label = "TRANSACTIONS",
                            to = "",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7081)
                        },
                        new
                        {
                            id = 5,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7083),
                            icon = "database",
                            label = "MASTER DATA",
                            to = "",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7083)
                        },
                        new
                        {
                            id = 6,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7085),
                            icon = "user",
                            label = "User Accounts",
                            parentId = 1,
                            to = "/system/users",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7085)
                        },
                        new
                        {
                            id = 7,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7086),
                            icon = "users",
                            label = "User Groups",
                            parentId = 1,
                            to = "/system/groups",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7087)
                        },
                        new
                        {
                            id = 8,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7088),
                            icon = "user-check",
                            label = "Employee Management",
                            parentId = 2,
                            to = "/employee/manage",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7088)
                        },
                        new
                        {
                            id = 9,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7090),
                            icon = "sliders",
                            label = "Administration",
                            parentId = 3,
                            to = "/admin/settings",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7090)
                        },
                        new
                        {
                            id = 10,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7091),
                            icon = "file-text",
                            label = "Orders",
                            parentId = 4,
                            to = "/transactions/orders",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7091)
                        },
                        new
                        {
                            id = 11,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7093),
                            icon = "file-invoice",
                            label = "Invoice Management",
                            parentId = 4,
                            to = "/transactions/invoices",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7093)
                        },
                        new
                        {
                            id = 12,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7094),
                            icon = "tag",
                            label = "Product Categories",
                            parentId = 5,
                            to = "/master/product-categories",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7094)
                        },
                        new
                        {
                            id = 13,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7096),
                            icon = "users",
                            label = "Customer Categories",
                            parentId = 5,
                            to = "/master/customer-categories",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7096)
                        },
                        new
                        {
                            id = 14,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7097),
                            icon = "user",
                            label = "Customer Master",
                            parentId = 5,
                            to = "/master/customers",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(7097)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "department");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "userCode");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "userName");

                    b.HasKey("id");

                    b.HasIndex("userCode")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(6886),
                            department = "Ban Giám Đốc",
                            email = "admin@test.com",
                            password = "123",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(6889),
                            userCode = "NV001",
                            userName = "admin"
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(6896),
                            department = "Khoa Nội",
                            email = "bs@test.com",
                            password = "123",
                            updatedAt = new DateTime(2026, 8, 6, 6, 35, 19, 321, DateTimeKind.Utc).AddTicks(6896),
                            userCode = "BS001",
                            userName = "bacsi01"
                        });
                });

            modelBuilder.Entity("AppActionGroup", b =>
                {
                    b.HasOne("THUCTAP.Models.AppAction", null)
                        .WithMany()
                        .HasForeignKey("actionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.Menu", null)
                        .WithMany()
                        .HasForeignKey("menuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.User", null)
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("THUCTAP.Models.AppAction", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "menu")
                        .WithMany("action")
                        .HasForeignKey("menuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");
                });

            modelBuilder.Entity("THUCTAP.Models.FormField", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("menuId");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "parent")
                        .WithMany("children")
                        .HasForeignKey("parentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("parent");
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.Navigation("action");

                    b.Navigation("children");
                });
#pragma warning restore 612, 618
        }
    }
}
