// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THUCTAP.Data;

#nullable disable

namespace THUCTAP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828083343_dbchangeinEM")]
    partial class dbchangeinEM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Group_Action", b =>
                {
                    b.Property<int>("actionid")
                        .HasColumnType("int");

                    b.Property<int>("groupid")
                        .HasColumnType("int");

                    b.HasKey("actionid", "groupid");

                    b.HasIndex("groupid");

                    b.ToTable("Group_Action");

                    b.HasData(
                        new
                        {
                            actionid = 1,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 2,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 3,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 4,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 5,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 1,
                            groupid = 2
                        },
                        new
                        {
                            actionid = 2,
                            groupid = 2
                        },
                        new
                        {
                            actionid = 4,
                            groupid = 2
                        },
                        new
                        {
                            actionid = 1,
                            groupid = 3
                        });
                });

            modelBuilder.Entity("Group_Menu", b =>
                {
                    b.Property<int>("groupid")
                        .HasColumnType("int");

                    b.Property<int>("menuid")
                        .HasColumnType("int");

                    b.HasKey("groupid", "menuid");

                    b.HasIndex("menuid");

                    b.ToTable("Group_Menu");

                    b.HasData(
                        new
                        {
                            groupid = 1,
                            menuid = 1
                        },
                        new
                        {
                            groupid = 1,
                            menuid = 2
                        },
                        new
                        {
                            groupid = 2,
                            menuid = 2
                        },
                        new
                        {
                            groupid = 2,
                            menuid = 8
                        },
                        new
                        {
                            groupid = 3,
                            menuid = 2
                        },
                        new
                        {
                            groupid = 3,
                            menuid = 8
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.AppAction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "endpoint");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int>("menuId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "menuId");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "method");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("menuId");

                    b.ToTable("Actions");

                    b.HasAnnotation("Relational:JsonPropertyName", "action");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "VIEW",
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endpoint = "/api/users",
                            isActive = true,
                            label = "View",
                            menuId = 6,
                            method = "GET",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            code = "CREATE",
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endpoint = "/api/users",
                            isActive = true,
                            label = "Create",
                            menuId = 6,
                            method = "POST",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            code = "EDIT",
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endpoint = "/api/users/{id}",
                            isActive = true,
                            label = "Update",
                            menuId = 6,
                            method = "PUT",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 4,
                            code = "DELETE",
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endpoint = "/api/users/{id}",
                            isActive = true,
                            label = "Delete",
                            menuId = 6,
                            method = "DELETE",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 5,
                            code = "VIEW",
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endpoint = "/api/groups",
                            isActive = true,
                            label = "View",
                            menuId = 7,
                            method = "GET",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 6,
                            code = "CREATE",
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endpoint = "/api/groups",
                            isActive = true,
                            label = "Create",
                            menuId = 7,
                            method = "POST",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 7,
                            code = "EDIT",
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endpoint = "/api/groups/{id}",
                            isActive = true,
                            label = "Update",
                            menuId = 7,
                            method = "PUT",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 8,
                            code = "DELETE",
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endpoint = "/api/groups/{id}",
                            isActive = true,
                            label = "Delete",
                            menuId = 7,
                            method = "DELETE",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.CustomerCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("groupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("CustomerCategories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            discount = 15.0m,
                            groupName = "Khách hàng V.I.P",
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            discount = 10.0m,
                            groupName = "Khách mua sỉ",
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            createdAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            discount = 0.0m,
                            groupName = "Khách vãng lai",
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 4,
                            createdAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            discount = 5.0m,
                            groupName = "Khách hàng thân thiết",
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 5,
                            createdAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            discount = 20.0m,
                            groupName = "Đối tác chiến lược",
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.CustomerMaster", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("engineerInCharge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("supplierAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplierEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplierPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.ToTable("CustomerMasters");

                    b.HasData(
                        new
                        {
                            id = 1,
                            categoryId = 1,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            engineerInCharge = "Lê Văn C",
                            isActive = true,
                            supplierAddress = "Quận 3, TP.HCM",
                            supplierEmail = "support@medjin.com",
                            supplierName = "Công ty TBYT MedJin",
                            supplierPhone = "0988777666",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            categoryId = 2,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            engineerInCharge = "Nguyễn Văn A",
                            isActive = true,
                            supplierAddress = "Quận 1, TP.HCM",
                            supplierEmail = "contact@abc.com",
                            supplierName = "Công ty TBYT ABC",
                            supplierPhone = "0909123456",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Equipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<int>("productCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("productCategoryId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            productCategoryId = 1,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            productCategoryId = 2,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            productCategoryId = 3,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.EquipmentMaintenance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("actionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("completedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("engineerArrivedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("engineerSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("equipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("incidentTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("labSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("maintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("equipmentId");

                    b.ToTable("EquipmentMaintenances");

                    b.HasData(
                        new
                        {
                            id = 1,
                            actionType = "Bảo trì",
                            completedTime = new DateTime(2026, 10, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            content = "Vệ sinh buồng ly tâm, kiểm tra rotor",
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            engineerArrivedTime = new DateTime(2026, 10, 15, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            engineerSignature = "Nguyễn Văn A",
                            equipmentId = 1,
                            isActive = true,
                            labSignature = "Đã ký",
                            maintenanceDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            purpose = "Bảo trì định kỳ 6 tháng",
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            actionType = "Sửa chữa",
                            completedTime = new DateTime(2026, 12, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            content = "Thay thế bo mạch nguồn",
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            engineerArrivedTime = new DateTime(2026, 12, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            engineerSignature = "Trần Văn B",
                            equipmentId = 1,
                            incidentTime = new DateTime(2026, 12, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            labSignature = "Đã ký",
                            maintenanceDate = new DateTime(2026, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            purpose = "Khắc phục lỗi không lên nguồn",
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            actionType = "Hiệu chuẩn",
                            completedTime = new DateTime(2026, 11, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            content = "Hiệu chuẩn cảm biến áp suất",
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            engineerArrivedTime = new DateTime(2026, 11, 20, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            engineerSignature = "Lê Văn C",
                            equipmentId = 2,
                            isActive = true,
                            labSignature = "Đã ký",
                            maintenanceDate = new DateTime(2026, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            purpose = "Đảm bảo độ chính xác",
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 4,
                            actionType = "Sửa chữa",
                            completedTime = new DateTime(2026, 11, 25, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            content = "Thay bộ lọc khí",
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            engineerArrivedTime = new DateTime(2026, 11, 25, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            engineerSignature = "Trần Văn B",
                            equipmentId = 3,
                            incidentTime = new DateTime(2026, 11, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            labSignature = "Đã ký",
                            maintenanceDate = new DateTime(2026, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            purpose = "Máy kêu to",
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.EquipmentMaintenanceLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("equipmentId")
                        .HasColumnType("int");

                    b.Property<int>("executorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("inspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("inspectorId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isAsNeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("isDaily")
                        .HasColumnType("bit");

                    b.Property<bool>("isMonthly")
                        .HasColumnType("bit");

                    b.Property<bool>("isQuarterly")
                        .HasColumnType("bit");

                    b.Property<bool>("isWeekly")
                        .HasColumnType("bit");

                    b.Property<DateTime>("logDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("relatedMaintenanceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("reviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("reviewerId")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("equipmentId");

                    b.HasIndex("executorId");

                    b.HasIndex("inspectorId");

                    b.HasIndex("relatedMaintenanceId");

                    b.HasIndex("reviewerId");

                    b.ToTable("EquipmentMaintenanceLogs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 2,
                            inspectionDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "Máy hoạt động bình thường",
                            reviewDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reviewerId = 1,
                            status = 3,
                            updatedAt = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 2,
                            inspectionDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "Vệ sinh buồng mẫu",
                            reviewDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reviewerId = 1,
                            status = 3,
                            updatedAt = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            createdAt = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 2,
                            inspectionDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "",
                            reviewDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reviewerId = 1,
                            status = 3,
                            updatedAt = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 4,
                            createdAt = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 3,
                            inspectionDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "Chạy mẫu test OK",
                            reviewDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reviewerId = 1,
                            status = 3,
                            updatedAt = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 5,
                            createdAt = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 3,
                            inspectionDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "",
                            reviewDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reviewerId = 1,
                            status = 3,
                            updatedAt = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 6,
                            createdAt = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 3,
                            inspectionDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "",
                            reviewDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reviewerId = 1,
                            status = 3,
                            updatedAt = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 7,
                            createdAt = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 2,
                            inspectionDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = true,
                            logDate = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "Bảo dưỡng cuối tuần, xả sương",
                            reviewDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reviewerId = 1,
                            status = 3,
                            updatedAt = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 8,
                            createdAt = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 3,
                            inspectionDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "",
                            status = 2,
                            updatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 9,
                            createdAt = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 3,
                            inspectionDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "",
                            status = 2,
                            updatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 10,
                            createdAt = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 2,
                            inspectionDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = true,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "Lỗi bo mạch, đã gọi kỹ sư",
                            relatedMaintenanceId = 2,
                            status = 2,
                            updatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 11,
                            createdAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 2,
                            inspectionDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "Máy đã sửa xong, chạy ổn",
                            status = 2,
                            updatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 12,
                            createdAt = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 3,
                            inspectionDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "",
                            status = 2,
                            updatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 13,
                            createdAt = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 3,
                            inspectionDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "",
                            status = 2,
                            updatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 14,
                            createdAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 2,
                            inspectionDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inspectorId = 1,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = true,
                            logDate = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "Bảo dưỡng cuối tuần",
                            status = 2,
                            updatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 15,
                            createdAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            executorId = 2,
                            isActive = true,
                            isAsNeeded = false,
                            isDaily = true,
                            isMonthly = false,
                            isQuarterly = false,
                            isWeekly = false,
                            logDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            note = "Khởi động đầu ca tốt",
                            status = 1,
                            updatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.EquipmentManager", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("equipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fromDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("equipmentId");

                    b.HasIndex("userId");

                    b.ToTable("EquipmentManagers");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            fromDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userId = 1,
                            userName = "admin"
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            fromDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userId = 2,
                            userName = "bacsi01"
                        },
                        new
                        {
                            id = 3,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 1,
                            fromDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userId = 3,
                            userName = "admin02"
                        },
                        new
                        {
                            id = 4,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 2,
                            fromDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userId = 1,
                            userName = "admin"
                        },
                        new
                        {
                            id = 5,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 2,
                            fromDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userId = 2,
                            userName = "bacsi01"
                        },
                        new
                        {
                            id = 6,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 2,
                            fromDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userId = 4,
                            userName = "Nguyễn Văn An"
                        },
                        new
                        {
                            id = 7,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 3,
                            fromDate = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userId = 2,
                            userName = "bacsi01"
                        },
                        new
                        {
                            id = 8,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 3,
                            fromDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userId = 3,
                            userName = "admin02"
                        },
                        new
                        {
                            id = 9,
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            equipmentId = 3,
                            fromDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userId = 4,
                            userName = "Nguyễn Văn An"
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.FormField", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("colSpan")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "colSpan");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("entityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "entityName");

                    b.Property<string>("field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "field");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isSearchAble")
                        .HasColumnType("bit");

                    b.Property<bool>("isShowInForm")
                        .HasColumnType("bit");

                    b.Property<bool>("isShowInList")
                        .HasColumnType("bit");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int?>("menuId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "menuId");

                    b.Property<string>("option")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "option");

                    b.Property<int>("sortOrder")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "sortOrder");

                    b.Property<string>("subField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tabName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tagField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("menuId");

                    b.ToTable("FormFields");

                    b.HasData(
                        new
                        {
                            id = 1,
                            colSpan = 6,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            entityName = "User",
                            field = "username",
                            isActive = true,
                            isSearchAble = false,
                            isShowInForm = false,
                            isShowInList = false,
                            label = "Tên đăng nhập",
                            option = "",
                            sortOrder = 1,
                            type = "text",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            colSpan = 6,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            entityName = "User",
                            field = "department",
                            isActive = true,
                            isSearchAble = false,
                            isShowInForm = false,
                            isShowInList = false,
                            label = "Phòng ban",
                            option = "",
                            sortOrder = 2,
                            type = "select",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Group", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "ADMIN",
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            name = "Quản trị hệ thống",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            code = "DOCTOR",
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            name = "Bác sĩ",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            code = "Employee",
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            name = "Nhân viên",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "icon");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int?>("parentId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "parentId");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "to");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("parentId");

                    b.ToTable("Menus");

                    b.HasAnnotation("Relational:JsonPropertyName", "children");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "shield",
                            isActive = true,
                            label = "SECURITY & SYSTEM",
                            to = "",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "users",
                            isActive = true,
                            label = "EMPLOYEE MANAGEMENT",
                            to = "",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "settings",
                            isActive = true,
                            label = "ADMINISTRATION",
                            to = "",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 4,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "shopping-cart",
                            isActive = true,
                            label = "TRANSACTIONS",
                            to = "",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 5,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "database",
                            isActive = true,
                            label = "MASTER DATA",
                            to = "",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 6,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "user",
                            isActive = true,
                            label = "User Accounts",
                            parentId = 1,
                            to = "/system/users",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 7,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "users",
                            isActive = true,
                            label = "User Groups",
                            parentId = 1,
                            to = "/system/groups",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 8,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "user-check",
                            isActive = true,
                            label = "Employee Management",
                            parentId = 2,
                            to = "/employee/manage",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 9,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "sliders",
                            isActive = true,
                            label = "Administration",
                            parentId = 3,
                            to = "/admin/settings",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 10,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "file-text",
                            isActive = true,
                            label = "Orders",
                            parentId = 4,
                            to = "/transactions/orders",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 11,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "file-invoice",
                            isActive = true,
                            label = "Invoice Management",
                            parentId = 4,
                            to = "/transactions/invoices",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 12,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "tag",
                            isActive = true,
                            label = "Product Categories",
                            parentId = 5,
                            to = "/master/product-categories",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 13,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "users",
                            isActive = true,
                            label = "Customer Categories",
                            parentId = 5,
                            to = "/master/customer-categories",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 14,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            icon = "user",
                            isActive = true,
                            label = "Customer Master",
                            parentId = 5,
                            to = "/master/customers",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<decimal>("estimatedTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("orderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("customerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            customerId = 1,
                            estimatedTotal = 2500000m,
                            isActive = true,
                            orderDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            orderNumber = "ORD-2026-001",
                            updatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            customerId = 2,
                            estimatedTotal = 2600000m,
                            isActive = true,
                            orderDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            orderNumber = "ORD-2026-002",
                            updatedAt = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            createdAt = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            customerId = 4,
                            estimatedTotal = 2700000m,
                            isActive = true,
                            orderDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            orderNumber = "ORD-2026-003",
                            updatedAt = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 4,
                            createdAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            customerId = 1,
                            estimatedTotal = 2800000m,
                            isActive = true,
                            orderDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            orderNumber = "ORD-2026-004",
                            updatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 5,
                            createdAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            customerId = 3,
                            estimatedTotal = 2900000m,
                            isActive = true,
                            orderDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            orderNumber = "ORD-2026-005",
                            updatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.ProductCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("asNeededTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("conditionWhenReceived")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("conditionWhenStarted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countryOfOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dailyTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monthlyTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quarterlyTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("receivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("serialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("startDateOfUse")
                        .HasColumnType("datetime2");

                    b.Property<int>("supplierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weeklyTask")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("supplierId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            asNeededTask = "Thay thế linh kiện",
                            conditionWhenReceived = "Mới 100%",
                            conditionWhenStarted = "Hoạt động tốt",
                            countryOfOrigin = "Đức",
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dailyTask = "Kiểm tra hoạt động máy",
                            equipmentCode = "TB-XN-01",
                            equipmentName = "Máy ly tâm Huyết học",
                            isActive = true,
                            location = "Phòng Xét nghiệm Hóa sinh",
                            manufacturer = "BioTech Lab",
                            model = "CENT-200",
                            monthlyTask = "Tra dầu rotor",
                            quarterlyTask = "Bảo trì động cơ",
                            receivedDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            serialNumber = "SN-2026001",
                            startDateOfUse = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            supplierId = 1,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            weeklyTask = "Vệ sinh buồng ly tâm"
                        },
                        new
                        {
                            id = 2,
                            asNeededTask = "Thay pin/vòng bít",
                            conditionWhenReceived = "Mới 100%",
                            conditionWhenStarted = "Hoạt động tốt",
                            countryOfOrigin = "Nhật Bản",
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dailyTask = "Kiểm tra pin và nguồn",
                            equipmentCode = "HA-OM-01",
                            equipmentName = "Máy đo huyết áp điện tử",
                            isActive = true,
                            location = "Phòng Khám Nội",
                            manufacturer = "Omron",
                            model = "HEM-7120",
                            monthlyTask = "Kiểm tra vòng bít",
                            quarterlyTask = "Đo kiểm định kỳ",
                            receivedDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            serialNumber = "SN-2026002",
                            startDateOfUse = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            supplierId = 2,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            weeklyTask = "Vệ sinh màn hình"
                        },
                        new
                        {
                            id = 3,
                            asNeededTask = "Thay hạt zeolite",
                            conditionWhenReceived = "Mới 100%",
                            conditionWhenStarted = "Hoạt động tốt",
                            countryOfOrigin = "Trung Quốc",
                            createdAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dailyTask = "Kiểm tra lưu lượng oxy",
                            equipmentCode = "OXY-5L-01",
                            equipmentName = "Máy tạo oxy 5 Lít",
                            isActive = true,
                            location = "Phòng Cấp Cứu",
                            manufacturer = "Yuwell",
                            model = "OXY-5",
                            monthlyTask = "Thay bộ lọc thô",
                            quarterlyTask = "Bảo trì động cơ nén",
                            receivedDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            serialNumber = "SN-2026003",
                            startDateOfUse = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            supplierId = 1,
                            updatedAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            weeklyTask = "Vệ sinh bình làm ẩm"
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "department");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "userCode");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "userName");

                    b.HasKey("id");

                    b.HasIndex("userCode")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            department = "Ban Giám Đốc",
                            email = "admin@test.com",
                            isActive = true,
                            password = "123",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userCode = "NV001",
                            userName = "admin"
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            department = "Khoa Nội",
                            email = "bs@test.com",
                            isActive = true,
                            password = "123",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userCode = "BS001",
                            userName = "bacsi01"
                        });
                });

            modelBuilder.Entity("User_Group", b =>
                {
                    b.Property<int>("groupid")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("groupid", "userid");

                    b.HasIndex("userid");

                    b.ToTable("User_Group");

                    b.HasData(
                        new
                        {
                            groupid = 1,
                            userid = 1
                        },
                        new
                        {
                            groupid = 2,
                            userid = 2
                        });
                });

            modelBuilder.Entity("Group_Action", b =>
                {
                    b.HasOne("THUCTAP.Models.AppAction", null)
                        .WithMany()
                        .HasForeignKey("actionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group_Menu", b =>
                {
                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.Menu", null)
                        .WithMany()
                        .HasForeignKey("menuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("THUCTAP.Models.AppAction", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "menu")
                        .WithMany("action")
                        .HasForeignKey("menuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");
                });

            modelBuilder.Entity("THUCTAP.Models.CustomerMaster", b =>
                {
                    b.HasOne("THUCTAP.Models.CustomerCategory", "Category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("THUCTAP.Models.Equipment", b =>
                {
                    b.HasOne("THUCTAP.Models.ProductCategory", "productCategory")
                        .WithMany()
                        .HasForeignKey("productCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("productCategory");
                });

            modelBuilder.Entity("THUCTAP.Models.EquipmentMaintenance", b =>
                {
                    b.HasOne("THUCTAP.Models.Equipment", "equipment")
                        .WithMany("maintenances")
                        .HasForeignKey("equipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("equipment");
                });

            modelBuilder.Entity("THUCTAP.Models.EquipmentMaintenanceLog", b =>
                {
                    b.HasOne("THUCTAP.Models.Equipment", "equipment")
                        .WithMany()
                        .HasForeignKey("equipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.User", "executor")
                        .WithMany()
                        .HasForeignKey("executorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.User", "inspector")
                        .WithMany()
                        .HasForeignKey("inspectorId");

                    b.HasOne("THUCTAP.Models.EquipmentMaintenance", "relatedMaintenance")
                        .WithMany()
                        .HasForeignKey("relatedMaintenanceId");

                    b.HasOne("THUCTAP.Models.User", "reviewer")
                        .WithMany()
                        .HasForeignKey("reviewerId");

                    b.Navigation("equipment");

                    b.Navigation("executor");

                    b.Navigation("inspector");

                    b.Navigation("relatedMaintenance");

                    b.Navigation("reviewer");
                });

            modelBuilder.Entity("THUCTAP.Models.EquipmentManager", b =>
                {
                    b.HasOne("THUCTAP.Models.Equipment", "equipment")
                        .WithMany("managers")
                        .HasForeignKey("equipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("equipment");

                    b.Navigation("user");
                });

            modelBuilder.Entity("THUCTAP.Models.FormField", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "menu")
                        .WithMany("formFields")
                        .HasForeignKey("menuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("menu");
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "parent")
                        .WithMany("children")
                        .HasForeignKey("parentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("parent");
                });

            modelBuilder.Entity("THUCTAP.Models.Order", b =>
                {
                    b.HasOne("THUCTAP.Models.CustomerMaster", "customer")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("THUCTAP.Models.ProductCategory", b =>
                {
                    b.HasOne("THUCTAP.Models.CustomerMaster", "supplier")
                        .WithMany()
                        .HasForeignKey("supplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("User_Group", b =>
                {
                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.User", null)
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("THUCTAP.Models.Equipment", b =>
                {
                    b.Navigation("maintenances");

                    b.Navigation("managers");
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.Navigation("action");

                    b.Navigation("children");

                    b.Navigation("formFields");
                });
#pragma warning restore 612, 618
        }
    }
}
