// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THUCTAP.Data;

#nullable disable

namespace THUCTAP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810084804_ForeignkeyMenuIdForFormField")]
    partial class ForeignkeyMenuIdForFormField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppActionGroup", b =>
                {
                    b.Property<int>("actionid")
                        .HasColumnType("int");

                    b.Property<int>("groupid")
                        .HasColumnType("int");

                    b.HasKey("actionid", "groupid");

                    b.HasIndex("groupid");

                    b.ToTable("Group_Action", (string)null);

                    b.HasData(
                        new
                        {
                            actionid = 1,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 2,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 3,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 4,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 5,
                            groupid = 1
                        },
                        new
                        {
                            actionid = 1,
                            groupid = 2
                        },
                        new
                        {
                            actionid = 2,
                            groupid = 2
                        },
                        new
                        {
                            actionid = 4,
                            groupid = 2
                        },
                        new
                        {
                            actionid = 1,
                            groupid = 3
                        });
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.Property<int>("groupid")
                        .HasColumnType("int");

                    b.Property<int>("menuid")
                        .HasColumnType("int");

                    b.HasKey("groupid", "menuid");

                    b.HasIndex("menuid");

                    b.ToTable("Group_Menu", (string)null);

                    b.HasData(
                        new
                        {
                            groupid = 1,
                            menuid = 1
                        },
                        new
                        {
                            groupid = 1,
                            menuid = 2
                        },
                        new
                        {
                            groupid = 2,
                            menuid = 2
                        },
                        new
                        {
                            groupid = 2,
                            menuid = 8
                        },
                        new
                        {
                            groupid = 3,
                            menuid = 2
                        },
                        new
                        {
                            groupid = 3,
                            menuid = 8
                        });
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<int>("groupid")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("groupid", "userid");

                    b.HasIndex("userid");

                    b.ToTable("User_Group", (string)null);

                    b.HasData(
                        new
                        {
                            groupid = 1,
                            userid = 1
                        },
                        new
                        {
                            groupid = 2,
                            userid = 2
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.AppAction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "endpoint");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int>("menuId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "menuId");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "method");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("menuId");

                    b.ToTable("Actions");

                    b.HasAnnotation("Relational:JsonPropertyName", "action");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "VIEW",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7131),
                            endpoint = "/api/users",
                            label = "View",
                            menuId = 6,
                            method = "GET",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7131)
                        },
                        new
                        {
                            id = 2,
                            code = "DETAIL",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7135),
                            endpoint = "/api/users/{id}",
                            label = "Detail",
                            menuId = 6,
                            method = "GET",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7135)
                        },
                        new
                        {
                            id = 3,
                            code = "CREATE",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7136),
                            endpoint = "/api/users",
                            label = "Create",
                            menuId = 6,
                            method = "POST",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7136)
                        },
                        new
                        {
                            id = 4,
                            code = "EDIT",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7138),
                            endpoint = "/api/users/{id}",
                            label = "Update",
                            menuId = 6,
                            method = "PUT",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7138)
                        },
                        new
                        {
                            id = 5,
                            code = "DELETE",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7139),
                            endpoint = "/api/users/{id}",
                            label = "Delete",
                            menuId = 6,
                            method = "DELETE",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7139)
                        },
                        new
                        {
                            id = 6,
                            code = "VIEW",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7140),
                            endpoint = "/api/groups",
                            label = "View",
                            menuId = 7,
                            method = "GET",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7141)
                        },
                        new
                        {
                            id = 7,
                            code = "CREATE",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7142),
                            endpoint = "/api/groups",
                            label = "Create",
                            menuId = 7,
                            method = "POST",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7142)
                        },
                        new
                        {
                            id = 8,
                            code = "EDIT",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7143),
                            endpoint = "/api/groups/{id}",
                            label = "Update",
                            menuId = 7,
                            method = "PUT",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7144)
                        },
                        new
                        {
                            id = 9,
                            code = "DELETE",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7145),
                            endpoint = "/api/groups/{id}",
                            label = "Delete",
                            menuId = 7,
                            method = "DELETE",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7145)
                        },
                        new
                        {
                            id = 10,
                            code = "DETAIL",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7146),
                            endpoint = "/api/groups/{id}",
                            label = "Detail",
                            menuId = 7,
                            method = "GET",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7146)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.FormField", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("colSpan")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "colSpan");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("entityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "entityName");

                    b.Property<string>("field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "field");

                    b.Property<bool>("isDetail")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isDetail");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int?>("menuId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "menuId");

                    b.Property<string>("option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "option");

                    b.Property<string>("optionLabel")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "optionLabel");

                    b.Property<string>("optionValue")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "optionValue");

                    b.Property<int>("sortOrder")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "sortOrder");

                    b.Property<string>("subField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "subField");

                    b.Property<string>("tabName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tabName");

                    b.Property<string>("tagField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tagField");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("menuId");

                    b.ToTable("FormFields");

                    b.HasData(
                        new
                        {
                            id = 1,
                            colSpan = 6,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7250),
                            entityName = "User",
                            field = "username",
                            isDetail = false,
                            label = "Tên đăng nhập",
                            option = "",
                            sortOrder = 1,
                            subField = "",
                            tabName = "",
                            tagField = "",
                            type = "text",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7250)
                        },
                        new
                        {
                            id = 2,
                            colSpan = 6,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7254),
                            entityName = "User",
                            field = "department",
                            isDetail = false,
                            label = "Phòng ban",
                            option = "",
                            sortOrder = 2,
                            subField = "",
                            tabName = "",
                            tagField = "",
                            type = "select",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7255)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Group", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "ADMIN",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7108),
                            name = "Quản trị hệ thống",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7109)
                        },
                        new
                        {
                            id = 2,
                            code = "DOCTOR",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7112),
                            name = "Bác sĩ",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7112)
                        },
                        new
                        {
                            id = 3,
                            code = "Employee",
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7113),
                            name = "Nhân viên",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7113)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "icon");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int?>("parentId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "parentId");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "to");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("parentId");

                    b.ToTable("Menus");

                    b.HasAnnotation("Relational:JsonPropertyName", "children");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7171),
                            icon = "shield",
                            label = "SECURITY & SYSTEM",
                            to = "",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7171)
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7177),
                            icon = "users",
                            label = "EMPLOYEE MANAGEMENT",
                            to = "",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7177)
                        },
                        new
                        {
                            id = 3,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7178),
                            icon = "settings",
                            label = "ADMINISTRATION",
                            to = "",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7179)
                        },
                        new
                        {
                            id = 4,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7180),
                            icon = "shopping-cart",
                            label = "TRANSACTIONS",
                            to = "",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7180)
                        },
                        new
                        {
                            id = 5,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7207),
                            icon = "database",
                            label = "MASTER DATA",
                            to = "",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7207)
                        },
                        new
                        {
                            id = 6,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7209),
                            icon = "user",
                            label = "User Accounts",
                            parentId = 1,
                            to = "/system/users",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7209)
                        },
                        new
                        {
                            id = 7,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7210),
                            icon = "users",
                            label = "User Groups",
                            parentId = 1,
                            to = "/system/groups",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7210)
                        },
                        new
                        {
                            id = 8,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7212),
                            icon = "user-check",
                            label = "Employee Management",
                            parentId = 2,
                            to = "/employee/manage",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7212)
                        },
                        new
                        {
                            id = 9,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7214),
                            icon = "sliders",
                            label = "Administration",
                            parentId = 3,
                            to = "/admin/settings",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7214)
                        },
                        new
                        {
                            id = 10,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7215),
                            icon = "file-text",
                            label = "Orders",
                            parentId = 4,
                            to = "/transactions/orders",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7216)
                        },
                        new
                        {
                            id = 11,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7217),
                            icon = "file-invoice",
                            label = "Invoice Management",
                            parentId = 4,
                            to = "/transactions/invoices",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7217)
                        },
                        new
                        {
                            id = 12,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7218),
                            icon = "tag",
                            label = "Product Categories",
                            parentId = 5,
                            to = "/master/product-categories",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7219)
                        },
                        new
                        {
                            id = 13,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7220),
                            icon = "users",
                            label = "Customer Categories",
                            parentId = 5,
                            to = "/master/customer-categories",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7220)
                        },
                        new
                        {
                            id = 14,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7222),
                            icon = "user",
                            label = "Customer Master",
                            parentId = 5,
                            to = "/master/customers",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(7222)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "department");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "userCode");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "userName");

                    b.HasKey("id");

                    b.HasIndex("userCode")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(6978),
                            department = "Ban Giám Đốc",
                            email = "admin@test.com",
                            password = "123",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(6981),
                            userCode = "NV001",
                            userName = "admin"
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(6986),
                            department = "Khoa Nội",
                            email = "bs@test.com",
                            password = "123",
                            updatedAt = new DateTime(2026, 8, 10, 8, 48, 3, 896, DateTimeKind.Utc).AddTicks(6986),
                            userCode = "BS001",
                            userName = "bacsi01"
                        });
                });

            modelBuilder.Entity("AppActionGroup", b =>
                {
                    b.HasOne("THUCTAP.Models.AppAction", null)
                        .WithMany()
                        .HasForeignKey("actionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.Menu", null)
                        .WithMany()
                        .HasForeignKey("menuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.User", null)
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("THUCTAP.Models.AppAction", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "menu")
                        .WithMany("action")
                        .HasForeignKey("menuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");
                });

            modelBuilder.Entity("THUCTAP.Models.FormField", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "menu")
                        .WithMany("formFields")
                        .HasForeignKey("menuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("menu");
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "parent")
                        .WithMany("children")
                        .HasForeignKey("parentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("parent");
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.Navigation("action");

                    b.Navigation("children");

                    b.Navigation("formFields");
                });
#pragma warning restore 612, 618
        }
    }
}
