// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THUCTAP.Data;

#nullable disable

namespace THUCTAP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730090234_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppActionGroup", b =>
                {
                    b.Property<int>("actionsid")
                        .HasColumnType("int");

                    b.Property<int>("groupsid")
                        .HasColumnType("int");

                    b.HasKey("actionsid", "groupsid");

                    b.HasIndex("groupsid");

                    b.ToTable("Group_Actions", (string)null);

                    b.HasData(
                        new
                        {
                            actionsid = 1,
                            groupsid = 1
                        },
                        new
                        {
                            actionsid = 2,
                            groupsid = 1
                        },
                        new
                        {
                            actionsid = 3,
                            groupsid = 1
                        },
                        new
                        {
                            actionsid = 4,
                            groupsid = 1
                        },
                        new
                        {
                            actionsid = 5,
                            groupsid = 1
                        });
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.Property<int>("groupsid")
                        .HasColumnType("int");

                    b.Property<int>("menusid")
                        .HasColumnType("int");

                    b.HasKey("groupsid", "menusid");

                    b.HasIndex("menusid");

                    b.ToTable("Group_Menus", (string)null);

                    b.HasData(
                        new
                        {
                            groupsid = 1,
                            menusid = 1
                        },
                        new
                        {
                            groupsid = 1,
                            menusid = 2
                        });
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<int>("groupsid")
                        .HasColumnType("int");

                    b.Property<int>("usersid")
                        .HasColumnType("int");

                    b.HasKey("groupsid", "usersid");

                    b.HasIndex("usersid");

                    b.ToTable("User_Groups", (string)null);

                    b.HasData(
                        new
                        {
                            groupsid = 1,
                            usersid = 1
                        },
                        new
                        {
                            groupsid = 2,
                            usersid = 2
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.AppAction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "endpoint");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int>("menuid")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "menuId");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "method");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("menuid");

                    b.ToTable("Actions");

                    b.HasAnnotation("Relational:JsonPropertyName", "actions");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "USER_VIEW_LIST",
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2924),
                            endpoint = "/api/users",
                            label = "Danh sách ",
                            menuid = 2,
                            method = "GET",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2925)
                        },
                        new
                        {
                            id = 2,
                            code = "USER_VIEW_DETAIL",
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2930),
                            endpoint = "/api/users/{id}",
                            label = "Chi tiết ",
                            menuid = 2,
                            method = "GET",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2930)
                        },
                        new
                        {
                            id = 3,
                            code = "USER_ADD",
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2932),
                            endpoint = "/api/users",
                            label = "Thêm mới ",
                            menuid = 2,
                            method = "POST",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2932)
                        },
                        new
                        {
                            id = 4,
                            code = "USER_EDIT",
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2933),
                            endpoint = "/api/users/{id}",
                            label = "Cập nhật ",
                            menuid = 2,
                            method = "PUT",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2934)
                        },
                        new
                        {
                            id = 5,
                            code = "USER_DEL",
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2935),
                            endpoint = "/api/users/{id}",
                            label = "Xóa ",
                            menuid = 2,
                            method = "DELETE",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2935)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.FormField", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("colspan")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "col_span");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("entityname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "entity_name");

                    b.Property<string>("field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "field");

                    b.Property<bool>("isdetail")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "is_detail");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<string>("optionlabel")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "option_label");

                    b.Property<string>("options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "options");

                    b.Property<string>("optionvalue")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "option_value");

                    b.Property<int>("sortorder")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "sort_order");

                    b.Property<string>("subfield")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "sub_field");

                    b.Property<string>("tabname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tab_name");

                    b.Property<string>("tagfield")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tag_field");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("FormFields");

                    b.HasData(
                        new
                        {
                            id = 1,
                            colspan = 6,
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2974),
                            entityname = "User",
                            field = "username",
                            isdetail = false,
                            label = "Tên đăng nhập",
                            options = "",
                            sortorder = 1,
                            subfield = "",
                            tabname = "",
                            tagfield = "",
                            type = "text",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2975)
                        },
                        new
                        {
                            id = 2,
                            colspan = 6,
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2979),
                            entityname = "User",
                            field = "department",
                            isdetail = false,
                            label = "Phòng ban",
                            options = "",
                            sortorder = 2,
                            subfield = "",
                            tabname = "",
                            tagfield = "",
                            type = "select",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2980)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Group", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "ADMIN",
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2897),
                            description = "Full quyền",
                            name = "Quản trị hệ thống",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2897)
                        },
                        new
                        {
                            id = 2,
                            code = "DOCTOR",
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2901),
                            description = "Quyền khám chữa bệnh",
                            name = "Bác sĩ",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2902)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "icon");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int?>("parentid")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "parentId");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "to");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("parentid");

                    b.ToTable("Menus");

                    b.HasAnnotation("Relational:JsonPropertyName", "children");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2952),
                            icon = "settings",
                            label = "Hệ thống",
                            to = "/system",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2952)
                        },
                        new
                        {
                            id = 2,
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2956),
                            icon = "users",
                            label = "Quản lý Người dùng",
                            parentid = 1,
                            to = "/system/users",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2956)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "department");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime2");

                    b.Property<string>("usercode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "user_code");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.HasKey("id");

                    b.HasIndex("usercode")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2798),
                            department = "Ban Giám Đốc",
                            email = "admin@test.com",
                            password = "123",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2802),
                            usercode = "NV001",
                            username = "admin"
                        },
                        new
                        {
                            id = 2,
                            createdat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2806),
                            department = "Khoa Nội",
                            email = "bs@test.com",
                            password = "123",
                            updatedat = new DateTime(2026, 7, 30, 9, 2, 34, 54, DateTimeKind.Utc).AddTicks(2806),
                            usercode = "BS001",
                            username = "bacsi01"
                        });
                });

            modelBuilder.Entity("AppActionGroup", b =>
                {
                    b.HasOne("THUCTAP.Models.AppAction", null)
                        .WithMany()
                        .HasForeignKey("actionsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.Menu", null)
                        .WithMany()
                        .HasForeignKey("menusid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.User", null)
                        .WithMany()
                        .HasForeignKey("usersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("THUCTAP.Models.AppAction", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "menu")
                        .WithMany("actions")
                        .HasForeignKey("menuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "parent")
                        .WithMany("children")
                        .HasForeignKey("parentid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("parent");
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.Navigation("actions");

                    b.Navigation("children");
                });
#pragma warning restore 612, 618
        }
    }
}
