// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THUCTAP.Data;

#nullable disable

namespace THUCTAP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731063613_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppActionGroup", b =>
                {
                    b.Property<int>("actionsid")
                        .HasColumnType("int");

                    b.Property<int>("groupsid")
                        .HasColumnType("int");

                    b.HasKey("actionsid", "groupsid");

                    b.HasIndex("groupsid");

                    b.ToTable("Group_Actions", (string)null);

                    b.HasData(
                        new
                        {
                            actionsid = 1,
                            groupsid = 1
                        },
                        new
                        {
                            actionsid = 2,
                            groupsid = 1
                        },
                        new
                        {
                            actionsid = 3,
                            groupsid = 1
                        },
                        new
                        {
                            actionsid = 4,
                            groupsid = 1
                        },
                        new
                        {
                            actionsid = 5,
                            groupsid = 1
                        });
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.Property<int>("groupsid")
                        .HasColumnType("int");

                    b.Property<int>("menusid")
                        .HasColumnType("int");

                    b.HasKey("groupsid", "menusid");

                    b.HasIndex("menusid");

                    b.ToTable("Group_Menus", (string)null);

                    b.HasData(
                        new
                        {
                            groupsid = 1,
                            menusid = 1
                        },
                        new
                        {
                            groupsid = 1,
                            menusid = 2
                        });
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<int>("groupsid")
                        .HasColumnType("int");

                    b.Property<int>("usersid")
                        .HasColumnType("int");

                    b.HasKey("groupsid", "usersid");

                    b.HasIndex("usersid");

                    b.ToTable("User_Groups", (string)null);

                    b.HasData(
                        new
                        {
                            groupsid = 1,
                            usersid = 1
                        },
                        new
                        {
                            groupsid = 2,
                            usersid = 2
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.AppAction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "endpoint");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int>("menuid")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "menuId");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "method");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("menuid");

                    b.ToTable("Actions");

                    b.HasAnnotation("Relational:JsonPropertyName", "actions");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "USER_VIEW_LIST",
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8024),
                            endpoint = "/api/users",
                            label = "Danh sách ",
                            menuid = 2,
                            method = "GET",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8024)
                        },
                        new
                        {
                            id = 2,
                            code = "USER_VIEW_DETAIL",
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8027),
                            endpoint = "/api/users/{id}",
                            label = "Chi tiết ",
                            menuid = 2,
                            method = "GET",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8028)
                        },
                        new
                        {
                            id = 3,
                            code = "USER_ADD",
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8029),
                            endpoint = "/api/users",
                            label = "Thêm mới ",
                            menuid = 2,
                            method = "POST",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8029)
                        },
                        new
                        {
                            id = 4,
                            code = "USER_EDIT",
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8030),
                            endpoint = "/api/users/{id}",
                            label = "Cập nhật ",
                            menuid = 2,
                            method = "PUT",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8031)
                        },
                        new
                        {
                            id = 5,
                            code = "USER_DEL",
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8032),
                            endpoint = "/api/users/{id}",
                            label = "Xóa ",
                            menuid = 2,
                            method = "DELETE",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8032)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.FormField", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("colspan")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "col_span");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("entityname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "entity_name");

                    b.Property<string>("field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "field");

                    b.Property<bool>("isdetail")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "is_detail");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<string>("optionlabel")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "option_label");

                    b.Property<string>("options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "options");

                    b.Property<string>("optionvalue")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "option_value");

                    b.Property<int>("sortorder")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "sort_order");

                    b.Property<string>("subfield")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "sub_field");

                    b.Property<string>("tabname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tab_name");

                    b.Property<string>("tagfield")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tag_field");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("FormFields");

                    b.HasData(
                        new
                        {
                            id = 1,
                            colspan = 6,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8178),
                            entityname = "User",
                            field = "username",
                            isdetail = false,
                            label = "Tên đăng nhập",
                            options = "",
                            sortorder = 1,
                            subfield = "",
                            tabname = "",
                            tagfield = "",
                            type = "text",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8178)
                        },
                        new
                        {
                            id = 2,
                            colspan = 6,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8181),
                            entityname = "User",
                            field = "department",
                            isdetail = false,
                            label = "Phòng ban",
                            options = "",
                            sortorder = 2,
                            subfield = "",
                            tabname = "",
                            tagfield = "",
                            type = "select",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8181)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Group", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "ADMIN",
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8001),
                            description = "Full quyền",
                            name = "Quản trị hệ thống",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8002)
                        },
                        new
                        {
                            id = 2,
                            code = "DOCTOR",
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8004),
                            description = "Quyền khám chữa bệnh",
                            name = "Bác sĩ",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8004)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "icon");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<int?>("parentid")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "parentId");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "to");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("parentid");

                    b.ToTable("Menus");

                    b.HasAnnotation("Relational:JsonPropertyName", "children");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8052),
                            icon = "shield",
                            label = "SECURITY & SYSTEM",
                            to = "",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8052)
                        },
                        new
                        {
                            id = 2,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8055),
                            icon = "users",
                            label = "EMPLOYEE MANAGEMENT",
                            to = "",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8055)
                        },
                        new
                        {
                            id = 3,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8057),
                            icon = "settings",
                            label = "ADMINISTRATION",
                            to = "",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8057)
                        },
                        new
                        {
                            id = 4,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8059),
                            icon = "shopping-cart",
                            label = "TRANSACTIONS",
                            to = "",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8059)
                        },
                        new
                        {
                            id = 5,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8060),
                            icon = "database",
                            label = "MASTER DATA",
                            to = "",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8060)
                        },
                        new
                        {
                            id = 6,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8061),
                            icon = "user",
                            label = "User Accounts",
                            parentid = 1,
                            to = "/system/users",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8061)
                        },
                        new
                        {
                            id = 7,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8063),
                            icon = "users",
                            label = "User Groups",
                            parentid = 1,
                            to = "/system/groups",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8063)
                        },
                        new
                        {
                            id = 8,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8064),
                            icon = "user-check",
                            label = "Employee Management",
                            parentid = 2,
                            to = "/employee/manage",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8064)
                        },
                        new
                        {
                            id = 9,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8066),
                            icon = "sliders",
                            label = "Administration",
                            parentid = 3,
                            to = "/admin/settings",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8066)
                        },
                        new
                        {
                            id = 10,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8067),
                            icon = "file-text",
                            label = "Orders",
                            parentid = 4,
                            to = "/transactions/orders",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8067)
                        },
                        new
                        {
                            id = 11,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8068),
                            icon = "file-invoice",
                            label = "Invoice Management",
                            parentid = 4,
                            to = "/transactions/invoices",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8069)
                        },
                        new
                        {
                            id = 12,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8070),
                            icon = "tag",
                            label = "Product Categories",
                            parentid = 5,
                            to = "/master/product-categories",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8070)
                        },
                        new
                        {
                            id = 13,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8148),
                            icon = "users",
                            label = "Customer Categories",
                            parentid = 5,
                            to = "/master/customer-categories",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8148)
                        },
                        new
                        {
                            id = 14,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8149),
                            icon = "user",
                            label = "Customer Master",
                            parentid = 5,
                            to = "/master/customers",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(8149)
                        });
                });

            modelBuilder.Entity("THUCTAP.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "department");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime2");

                    b.Property<string>("usercode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "user_code");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.HasKey("id");

                    b.HasIndex("usercode")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(7907),
                            department = "Ban Giám Đốc",
                            email = "admin@test.com",
                            password = "123",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(7910),
                            usercode = "NV001",
                            username = "admin"
                        },
                        new
                        {
                            id = 2,
                            createdat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(7917),
                            department = "Khoa Nội",
                            email = "bs@test.com",
                            password = "123",
                            updatedat = new DateTime(2026, 7, 31, 6, 36, 13, 536, DateTimeKind.Utc).AddTicks(7917),
                            usercode = "BS001",
                            username = "bacsi01"
                        });
                });

            modelBuilder.Entity("AppActionGroup", b =>
                {
                    b.HasOne("THUCTAP.Models.AppAction", null)
                        .WithMany()
                        .HasForeignKey("actionsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.Menu", null)
                        .WithMany()
                        .HasForeignKey("menusid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("THUCTAP.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THUCTAP.Models.User", null)
                        .WithMany()
                        .HasForeignKey("usersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("THUCTAP.Models.AppAction", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "menu")
                        .WithMany("actions")
                        .HasForeignKey("menuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.HasOne("THUCTAP.Models.Menu", "parent")
                        .WithMany("children")
                        .HasForeignKey("parentid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("parent");
                });

            modelBuilder.Entity("THUCTAP.Models.Menu", b =>
                {
                    b.Navigation("actions");

                    b.Navigation("children");
                });
#pragma warning restore 612, 618
        }
    }
}
